language: node_js
node_js:
  - 10
before_install:
  - openssl aes-256-cbc -K $encrypted_683f6e61624a_key -iv $encrypted_683f6e61624a_iv -in passwords.json.enc -out ./smap/routes/passwords.json -d
install:
  - cd smap
  - npm install
  - npm install -g codecov
script:
  - npm test
  - cd ..
  - codecov 
before_deploy:
  - cd smap
  - openssl aes-256-cbc -K $encrypted_6975539c574f_key -iv $encrypted_6975539c574f_iv -in keyfile.json.enc -out keyfile.json -d
deploy:
  provider: gae
  keyfile: keyfile.json
  project: swift-smap
  skip_cleanup: true